name:                haskell-scientist
version:             0.1.0.0
#synopsis:
#description:
homepage:            https://github.com/marcosh/haskell-scientist#readme
author:              Marco Perone
maintainer:          pasafama@gmail.com
copyright:           2020 Marco Perone
category:            Web
extra-source-files:
- README.md

dependencies:
  - base >= 4.7 && < 5
  - random

library:
  source-dirs:       src

tests:
  haskell-scientist-test:
    main:            Spec.hs
    source-dirs:     test
    dependencies:
      - haskell-scientist
      - hspec
      - QuickCheck
